version: '3'

services:
  postgres:
    image: postgres
    container_name: my-postgres-container
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: test
    volumes:
      - ./data:/var/lib/postgresql/data