spring:
  datasource:
    url: jdbc:postgresql://localhost:6432/postgres
    username: user
    password: password123

  flyway:
    enabled: true
    locations: classpath:db/migration
    url: jdbc:postgresql://localhost:6432/postgres
    user: user
    password: password123
